import type { Metadata } from "next";
import { SubpageHeader } from "../components";

export const metadata: Metadata = {
  title: "Privacy Policy — AI Gut Health & IBS Tracker",
};

export default function PrivacyPolicy() {
  return (
    <>
    <SubpageHeader />
    <article className="prose prose-gray mx-auto max-w-3xl px-6 py-12">
      <h1>Privacy Policy</h1>
      <p className="text-sm text-gray-500">Last updated: February 28, 2026</p>

      <p>
        Twin Tip Solutions LLC (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates the AI Gut
        Health &amp; IBS Tracker mobile application (the &quot;App&quot;). This Privacy
        Policy explains how we collect, use, and protect information when you use
        the App.
      </p>

      <h2>1. Anonymous Authentication</h2>
      <p>
        The App uses anonymous authentication exclusively. We do not collect your
        name, email address, phone number, or any other personally identifiable
        information (PII). When you first open the App, an anonymous user
        account is automatically created. This account is identified only by a
        randomly generated anonymous ID.
      </p>

      <h2>2. Information We Collect</h2>
      <p>
        The App collects the following data, associated only with your anonymous
        user ID:
      </p>
      <ul>
        <li>
          <strong>Meal Logs:</strong> Foods you log, meal types, FODMAP levels,
          serving sizes, and optional notes.
        </li>
        <li>
          <strong>Symptom Logs:</strong> Symptom types (bloating, gas, pain,
          heartburn, nausea, diarrhea, constipation, cramping), severity ratings,
          location, and notes.
        </li>
        <li>
          <strong>Poop Logs:</strong> Bristol Stool Chart classifications, color,
          urgency, and notes.
        </li>
        <li>
          <strong>FODMAP Tracking Data:</strong> Your current FODMAP elimination
          or reintroduction phase and related preferences.
        </li>
        <li>
          <strong>AI-Generated Data:</strong> Daily summaries, gut health scores,
          food-symptom correlations, and weekly insight reports generated by our
          AI system.
        </li>
        <li>
          <strong>Device Preferences:</strong> Reminder times, timezone, and
          notification settings.
        </li>
      </ul>

      <h2>3. Photos</h2>
      <p>
        You may optionally take photos of meals or bowel movements for AI
        analysis. When you take a photo:
      </p>
      <ul>
        <li>
          The photo is sent to Google&apos;s Gemini API for AI-powered analysis
          (food identification or Bristol Stool Chart classification).
        </li>
        <li>
          Photos are processed temporarily and are <strong>not</strong> stored
          permanently on our servers.
        </li>
        <li>
          Google&apos;s Gemini API may temporarily process the image data in
          accordance with Google&apos;s privacy policies.
        </li>
      </ul>

      <h2>4. How We Use Your Information</h2>
      <p>We use the information collected to:</p>
      <ul>
        <li>
          Provide the App&apos;s core features, including meal logging, symptom
          tracking, and poop tracking.
        </li>
        <li>
          Generate AI-powered analyses, including food-symptom correlations,
          daily gut health scores, and weekly insight reports.
        </li>
        <li>
          Send push notification reminders to log meals (if you enable
          notifications).
        </li>
        <li>Improve the App&apos;s functionality and user experience.</li>
      </ul>

      <h2>5. Data Storage</h2>
      <p>
        Your data is stored securely in Google Firebase Firestore, a cloud
        database operated by Google. All data is associated only with your
        anonymous user ID. Firebase uses industry-standard encryption for data in
        transit and at rest.
      </p>

      <h2>6. Analytics</h2>
      <p>
        We use Firebase Analytics to collect anonymized usage patterns, such as
        which features are used most frequently. This data does not identify you
        personally and is used solely to improve the App.
      </p>

      <h2>7. Third-Party Services</h2>
      <p>The App uses the following third-party services:</p>
      <ul>
        <li>
          <strong>Google Firebase:</strong> Authentication, database (Firestore),
          cloud storage, cloud functions, push notifications (FCM), and
          analytics.
        </li>
        <li>
          <strong>Google Gemini API:</strong> AI-powered food photo analysis and
          poop photo classification.
        </li>
      </ul>
      <p>
        These services have their own privacy policies. We encourage you to
        review Google&apos;s privacy policy at{" "}
        <a
          href="https://policies.google.com/privacy"
          target="_blank"
          rel="noopener noreferrer"
        >
          https://policies.google.com/privacy
        </a>
        .
      </p>

      <h2>8. Data Sharing</h2>
      <p>
        We do <strong>not</strong> sell, rent, or share your data with third
        parties for marketing or advertising purposes. Data is only shared with
        the third-party services listed above as necessary to provide the
        App&apos;s features.
      </p>

      <h2>9. Data Deletion</h2>
      <p>
        You can delete your data at any time through the App&apos;s settings. When
        you request data deletion, all meal logs, symptom logs, poop logs,
        correlations, summaries, and insights associated with your anonymous user
        ID are permanently removed from our systems.
      </p>

      <h2>10. Children&apos;s Privacy (COPPA)</h2>
      <p>
        The App is not intended for use by children under the age of 13. We do
        not knowingly collect information from children under 13. If we learn
        that we have collected data from a child under 13, we will delete that
        data promptly.
      </p>

      <h2>11. GDPR Compliance</h2>
      <p>
        For users in the European Economic Area (EEA), we note the following:
      </p>
      <ul>
        <li>
          <strong>Minimal data collection:</strong> We collect only the data
          necessary to provide the App&apos;s features.
        </li>
        <li>
          <strong>Anonymous by design:</strong> No personally identifiable
          information is collected.
        </li>
        <li>
          <strong>Right to deletion:</strong> You can delete all your data at any
          time through the App.
        </li>
        <li>
          <strong>Data portability:</strong> Because data is anonymous and tied
          to a device-specific ID, portability is inherently limited.
        </li>
      </ul>

      <h2>12. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. Changes will be
        posted within the App and on our website. Your continued use of the App
        after changes are posted constitutes acceptance of the updated policy.
      </p>

      <h2>13. Contact Us</h2>
      <p>
        If you have questions about this Privacy Policy, please contact us at:
      </p>
      <p>
        <strong>Twin Tip Solutions LLC</strong>
        <br />
        Email:{" "}
        <a href="mailto:reid@twintipsolutions.com">
          reid@twintipsolutions.com
        </a>
      </p>
    </article>
    </>
  );
}
