import type { Metadata } from "next";
import { SubpageHeader } from "../components";

export const metadata: Metadata = {
  title: "Privacy Policy — AI Gut Health & IBS Tracker",
};

export default function PrivacyPolicy() {
  return (
    <>
    <SubpageHeader />
    <article className="prose prose-gray mx-auto max-w-3xl px-6 py-12">
      <h1>Privacy Policy</h1>
      <p className="text-sm text-gray-500">
        Effective: March 11, 2026 &middot; Last updated: March 11, 2026
      </p>

      <p>
        Twin Tip Solutions LLC (&quot;we,&quot; &quot;us,&quot; or &quot;our&quot;) operates the AI Gut
        Health &amp; IBS Tracker mobile application (the &quot;App&quot;). This Privacy
        Policy explains how we collect, use, and protect information when you use
        the App.
      </p>

      <h2>1. Anonymous Authentication</h2>
      <p>
        The App uses anonymous authentication exclusively. We do not collect your
        name, email address, phone number, or any other personally identifiable
        information (PII). When you first open the App, an anonymous user
        account is automatically created. This account is identified only by a
        randomly generated anonymous ID.
      </p>

      <h2>2. Health &amp; Wellness Data</h2>
      <p>
        The App collects health-related wellness data to provide its core
        features. This data is associated only with your anonymous user ID and
        includes:
      </p>
      <ul>
        <li>
          <strong>Meal Logs:</strong> Foods you log, meal types, FODMAP levels,
          serving sizes, and optional notes.
        </li>
        <li>
          <strong>Symptom Logs:</strong> Symptom types (bloating, gas, pain,
          heartburn, nausea, diarrhea, constipation, cramping), severity ratings,
          location, and notes.
        </li>
        <li>
          <strong>Poop Logs:</strong> Bristol Stool Chart classifications, color,
          urgency, and notes.
        </li>
        <li>
          <strong>FODMAP Tracking Data:</strong> Your current FODMAP elimination
          or reintroduction phase and related preferences.
        </li>
        <li>
          <strong>AI-Generated Data:</strong> Daily summaries,
          food-symptom correlation reports, and insight reports generated by our
          AI system.
        </li>
        <li>
          <strong>Device Preferences:</strong> Reminder times, timezone, and
          notification settings.
        </li>
      </ul>
      <p>
        This data is <strong>not</strong> integrated with Apple HealthKit, Google
        Health Connect, or any other platform health framework. The App is an
        educational wellness tool and does not function as a medical device.
      </p>

      <h2>3. Photos</h2>
      <p>
        You may optionally take or select photos of meals or bowel movements for
        AI analysis. When you provide a photo:
      </p>
      <ul>
        <li>
          The photo is sent to Google&apos;s Gemini API via our Cloud Functions
          for AI-powered analysis (food identification or Bristol Stool Chart
          classification). The photo data is processed in memory and is not
          permanently stored by our Cloud Functions.
        </li>
        <li>
          After AI analysis, the original photo is uploaded to Google Firebase
          Cloud Storage and associated with your anonymous user ID. Meal photos
          are stored at <code>users/&#123;uid&#125;/meals/</code> and poop
          photos at <code>users/&#123;uid&#125;/poopLogs/</code>.
        </li>
        <li>
          Photos are retained until you delete the associated log entry or
          delete your account (see Section 10).
        </li>
        <li>
          Google&apos;s Gemini API may temporarily process the image data in
          accordance with Google&apos;s privacy policies.
        </li>
      </ul>

      <h2>4. How We Use Your Information</h2>
      <p>We use the information collected to:</p>
      <ul>
        <li>
          Provide the App&apos;s core features, including meal logging, symptom
          tracking, and poop tracking.
        </li>
        <li>
          Generate AI-powered analyses, including food-symptom correlation
          reports and daily summaries.
        </li>
        <li>
          Send push notification reminders to log meals (only if you enable
          notifications).
        </li>
        <li>Improve the App&apos;s functionality and user experience.</li>
      </ul>

      <h2>5. Data Storage &amp; Security</h2>
      <p>
        Your data is stored securely in Google Firebase (Firestore for structured
        data, Cloud Storage for photos), operated by Google Cloud Platform. All
        data is associated only with your anonymous user ID.
      </p>
      <ul>
        <li>
          <strong>Encryption in transit:</strong> All data transmitted between the
          App and our servers is encrypted using TLS (Transport Layer Security).
        </li>
        <li>
          <strong>Encryption at rest:</strong> Data stored in Firebase Firestore
          and Cloud Storage is encrypted at rest using Google&apos;s default
          encryption.
        </li>
        <li>
          <strong>Server-side processing:</strong> AI analysis is performed
          server-side via Firebase Cloud Functions. Photos and log data are not
          processed on-device by third-party AI models.
        </li>
      </ul>

      <h2>6. Data Retention</h2>
      <p>
        Your data is retained for as long as your anonymous account exists. Since
        accounts are anonymous and tied to your device, data persists until:
      </p>
      <ul>
        <li>You delete individual log entries through the App.</li>
        <li>You delete your account through the App&apos;s settings.</li>
        <li>
          You uninstall the App or reset your device (your anonymous account
          becomes orphaned and inaccessible).
        </li>
      </ul>
      <p>
        We may periodically purge orphaned anonymous accounts and their
        associated data that have been inactive for an extended period.
      </p>

      <h2>7. Third-Party Services</h2>
      <p>The App uses the following third-party services:</p>
      <ul>
        <li>
          <strong>Google Firebase:</strong> Authentication, database (Firestore),
          cloud storage, cloud functions, and push notifications (FCM).
        </li>
        <li>
          <strong>Google Gemini API (via Vertex AI):</strong> AI-powered food
          photo analysis, poop photo classification, and correlation report
          generation. Data sent to Gemini is processed under Google Cloud&apos;s
          data processing terms.
        </li>
      </ul>
      <p>
        We encourage you to review Google&apos;s privacy policy at{" "}
        <a
          href="https://policies.google.com/privacy"
          target="_blank"
          rel="noopener noreferrer"
        >
          https://policies.google.com/privacy
        </a>{" "}
        and Google Cloud&apos;s data processing terms at{" "}
        <a
          href="https://cloud.google.com/terms/data-processing-addendum"
          target="_blank"
          rel="noopener noreferrer"
        >
          https://cloud.google.com/terms/data-processing-addendum
        </a>
        .
      </p>

      <h2>8. Data Sharing</h2>
      <p>
        We do <strong>not</strong> sell, rent, or share your data with third
        parties for marketing or advertising purposes. Data is only shared with
        the third-party services listed above as necessary to provide the
        App&apos;s features.
      </p>

      <h2>9. Tracking &amp; Advertising</h2>
      <p>
        The App does <strong>not</strong> track you across other companies&apos;
        apps or websites. We do not use advertising identifiers (IDFA or GAID),
        do not display ads, and do not share data with ad networks or data
        brokers. The App does not participate in Apple&apos;s App Tracking
        Transparency framework because no cross-app tracking occurs.
      </p>

      <h2>10. Data Deletion</h2>
      <p>
        You can delete your data at any time through the App&apos;s settings.
        When you request account deletion, all meal logs, symptom logs, poop
        logs, photos, correlation reports, daily summaries, and preferences
        associated with your anonymous user ID are permanently removed from our
        systems, including Firebase Firestore and Cloud Storage.
      </p>

      <h2>11. Children&apos;s Privacy (COPPA)</h2>
      <p>
        The App is not intended for use by children under the age of 13. We do
        not knowingly collect information from children under 13. If we learn
        that we have collected data from a child under 13, we will delete that
        data promptly.
      </p>

      <h2>12. GDPR Compliance (EEA Users)</h2>
      <p>
        For users in the European Economic Area (EEA):
      </p>
      <ul>
        <li>
          <strong>Legal basis:</strong> We process your data based on legitimate
          interest in providing the App&apos;s wellness tracking features. For
          health-related data, processing is based on your explicit consent,
          which you provide by voluntarily logging health data in the App.
        </li>
        <li>
          <strong>Minimal data collection:</strong> We collect only the data
          necessary to provide the App&apos;s features.
        </li>
        <li>
          <strong>Anonymous by design:</strong> No personally identifiable
          information is collected.
        </li>
        <li>
          <strong>Right to deletion:</strong> You can delete all your data at any
          time through the App.
        </li>
        <li>
          <strong>Data portability:</strong> Because data is anonymous and tied
          to a device-specific ID, portability is inherently limited.
        </li>
        <li>
          <strong>Data transfers:</strong> Your data is processed and stored on
          Google Cloud servers which may be located outside the EEA. Google
          provides appropriate safeguards for international data transfers under
          their data processing terms.
        </li>
      </ul>

      <h2>13. CCPA Compliance (California Users)</h2>
      <p>
        For users in California, under the California Consumer Privacy Act
        (CCPA):
      </p>
      <ul>
        <li>
          <strong>Right to know:</strong> Section 2 of this policy describes the
          categories of information we collect.
        </li>
        <li>
          <strong>Right to delete:</strong> You can delete all your data through
          the App&apos;s settings at any time.
        </li>
        <li>
          <strong>No sale of data:</strong> We do not sell your personal
          information to third parties.
        </li>
        <li>
          <strong>No discrimination:</strong> We will not discriminate against
          you for exercising your CCPA rights.
        </li>
      </ul>

      <h2>14. Changes to This Policy</h2>
      <p>
        We may update this Privacy Policy from time to time. Changes will be
        posted within the App and on our website with an updated &quot;Last
        updated&quot; date. Your continued use of the App after changes are posted
        constitutes acceptance of the updated policy.
      </p>

      <h2>15. Contact Us</h2>
      <p>
        If you have questions about this Privacy Policy or wish to exercise your
        data rights, please contact us at:
      </p>
      <p>
        <strong>Twin Tip Solutions LLC</strong>
        <br />
        Email:{" "}
        <a href="mailto:reid@twintipsolutions.com">
          reid@twintipsolutions.com
        </a>
      </p>
    </article>
    </>
  );
}
